version: '3.2'
services:
  db2:
    image: cwds/db2data:latest
    # env_file: .env
    hostname: db2
    ports:
      - ${DB_CMS_DB2_PORT}:${DB_CMS_DB2_PORT}
    environment:
      DB2INST1_PASSWORD: ${DB_CMS_PASSWORD}
      LICENSE: "accept"
      DB2NAME: ${DB_CMS_DB_NAME}
  redis:
    image: redis
    ports:
      - "6379:6379"
  case-api:
    image: ${REPOSITORY}/case-management-api:latest
    hostname: casemanagement
    depends_on:
      - db2
    restart: on-failure
    ports:
      - ${CASE_API_PORT}:${CASE_API_PORT}
    # env_file: .env
    environment:
      SHIRO_CONFIG_PATH: ${SHIRO_NOSEC_CONFIG_PATH}
      KEY_STORE_FILE: ${KEY_STORE_FILE}
      DB_CMS_JDBC_URL: "jdbc:db2://db2:${DB_CMS_DB2_PORT}/${DB_CMS_DB_NAME}"
      DB_RS_JDBC_URL: "jdbc:db2://db2:${DB_CMS_DB2_PORT}/${DB_CMS_DB_NAME}"
  case-web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    volumes:
      - type: bind
        source: ./app
        target: /app/app
    ports:
      - "3000:3000"
      - "3035:3035"
    environment:
      - SECRET_KEY_BASE
      - CASE_API_BASE_URL
      - PERRY_API_BASE_URL
      - GEO_API_BASE_URL
    command: ['foreman', 'start', '-f', 'Procfile.dev.docker']
    depends_on:
      - redis
      - case-api
  case-test:
    build:
      context: .
      dockerfile: docker/test/Dockerfile
    volumes:
      - type: bind
        source: ./spec
        target: /app/spec
    # ports:
    #   - "3000:3000"
    #   - "3035:3035"
    environment:
      - SECRET_KEY_BASE
      - CASE_API_BASE_URL
      - PERRY_API_BASE_URL
      - CASE_WEB_BASE_URL
    #command: ['bundle', 'exec', 'rspec', 'spec/acceptance']
    depends_on:
      - case-web
      - case-api
